- name: Start an instance with a public IP address
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Launch EC2 instance
      amazon.aws.ec2_instance:
        name: "public-compute-instance two"
        key_name: "vprofile-key"
        vpc_subnet_id: subnet-071329f92dfb48bc5
        instance_type: t2.micro
        security_group: default
        network:
          assign_public_ip: true
        image_id: ami-0f599bbc07afc299a
        tags:
          Environment: Testing
      register: ec2_instance

    - name: Debug information
      debug:
        var: ec2_instance
