---
- name: Create EC2 Instance
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Launch EC2 Instance
      ec2_instance:
        key_name: vprofile-key
        instance_type: t2.micro
        image: ami-0f599bbc07afc299a  # Replace with your desired AMI ID
        wait: yes
        count: 1
        assign_public_ip: yes
        security_groups:
          - ansible-sg  # Replace with your security group name
      register: ec2

    - name: Print Public IP
      debug:
        var: ec2.instances[0].public_ip
